version: "2"

services:

  heiseidraw:
    build: ./
    container_name: heiseidraw
    restart: always
    environment:
      VIRTUAL_HOST: heiseidraw.walkingmask.tk
      LETSENCRYPT_HOST: heiseidraw.walkingmask.tk
      LETSENCRYPT_EMAIL: walkingmask@gmail.com
    volumes:
       - ./app:/app

networks:
  default:
    external:
      name: shared
